"""initial

Revision ID: 28bd09ae8148
Revises: 
Create Date: 2026-08-01 02:28:15.721143
"""
from alembic import op
import sqlalchemy as sa


revision = '28bd09ae8148'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mode', 'label', name='uq_account_mode_label')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_category_time', 'audit_events', ['category', 'occurred_at'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('high', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('low', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('close', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('volume', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'open_time', name='uq_candle')
    )
    op.create_index('ix_candles_lookup', 'candles', ['symbol', 'interval', 'open_time'], unique=False)
    op.create_table('config_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=16), nullable=False),
    sa.Column('quote_asset', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('step_size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('max_qty', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('min_notional', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('filters_raw', sa.JSON(), nullable=False),
    sa.Column('filters_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('free', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('locked', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('report_date', sa.String(length=10), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'report_date', name='uq_daily_report')
    )
    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('cash', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('exposure', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equity_time', 'equity_snapshots', ['account_id', 'taken_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('time_in_force', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('qty', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_exchange_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('stop_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('fees_paid', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('max_holding_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('limit_name', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('rejection_code', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_time', 'signals', ['created_at'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('exchange_trade_id', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('qty', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('fee_asset', sa.String(length=16), nullable=False),
    sa.Column('is_maker', sa.Boolean(), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'exchange_trade_id', name='uq_fill_dedupe')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fills')
    op.drop_index('ix_signals_time', table_name='signals')
    op.drop_table('signals')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_equity_time', table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    op.drop_table('daily_reports')
    op.drop_table('balance_snapshots')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('config_versions')
    op.drop_index('ix_candles_lookup', table_name='candles')
    op.drop_table('candles')
    op.drop_index('ix_audit_category_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('accounts')
    # ### end Alembic commands ###
