"""initial

Revision ID: 2b792b91116c
Revises: 28bd09ae8148
Create Date: 2026-08-01 02:32:06.151668
"""
from alembic import op
import sqlalchemy as sa


revision = '2b792b91116c'
down_revision = '28bd09ae8148'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
