"""sync models

Revision ID: 7d1ffe5b085f
Revises: d915b2c4286e
Create Date: 2026-08-01 05:11:48.939401
"""
from alembic import op
import sqlalchemy as sa


revision = '7d1ffe5b085f'
down_revision = 'd915b2c4286e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drill_acknowledgements',
    sa.Column('drill_name', sa.String(length=64), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('drill_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drill_acknowledgements')
    # ### end Alembic commands ###
