"""sync models

Revision ID: cd4c445295bb
Revises: 7d1ffe5b085f
Create Date: 2026-08-01 13:37:35.741021
"""
from alembic import op
import sqlalchemy as sa


revision = 'cd4c445295bb'
down_revision = '7d1ffe5b085f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
