"""sync models

Revision ID: d915b2c4286e
Revises: e89f06b277ad
Create Date: 2026-08-01 04:40:43.507540
"""
from alembic import op
import sqlalchemy as sa


revision = 'd915b2c4286e'
down_revision = 'e89f06b277ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
