"""sync models

Revision ID: e89f06b277ad
Revises: 2b792b91116c
Create Date: 2026-08-01 04:24:22.937503
"""
from alembic import op
import sqlalchemy as sa


revision = 'e89f06b277ad'
down_revision = '2b792b91116c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('route_reason', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_usage_time', 'ai_usage', ['created_at'], unique=False)
    op.create_table('pair_settings',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_per_trade', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('max_position_pct', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('min_confidence', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('allowed_strategies', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('explanation_mode', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('score', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('supporting', sa.JSON(), nullable=False),
    sa.Column('conflicting', sa.JSON(), nullable=False),
    sa.Column('entry_estimate', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('expected_holding_bars', sa.Integer(), nullable=True),
    sa.Column('est_fees', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('est_spread', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('est_slippage', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('expected_gross_return', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('expected_net_return', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_symbol_time', 'decisions', ['symbol', 'created_at'], unique=False)
    op.create_table('session_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('session_start_utc', sa.String(length=5), nullable=False),
    sa.Column('session_end_utc', sa.String(length=5), nullable=False),
    sa.Column('trading_days', sa.JSON(), nullable=False),
    sa.Column('overnight_policy', sa.String(length=24), nullable=False),
    sa.Column('daily_profit_target_pct', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('target_protection', sa.String(length=24), nullable=False),
    sa.Column('max_capital', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=False),
    sa.Column('data_timestamps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_messages_conv', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_messages_conv', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_table('session_configs')
    op.drop_index('ix_decisions_symbol_time', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('ai_conversations')
    op.drop_table('pair_settings')
    op.drop_index('ix_ai_usage_time', table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
